<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <?php /** @var \App\Models\Movie $movie */ ?>
    <title>Rezerwacja filmu <?=$movie->getTitle()?></title>
</head>
<body>
<h1>Rezerwacja filmu <?=$movie->getTitle()?>:</h1>
<form action="/reservations/create" method="POST">
    <input type="hidden" name="movie" value="<?=$movie->getId()?>">
    <table>
        <?php /** @var int $rows */ ?>
        <?php foreach (range(1, $rows) as $row): ?>
            <tr>
                <?php /** @var int $columns */ ?>
                <?php foreach (range(1, $columns) as $column): ?>
                    <td>
                        <input type="checkbox" name="seats[]" value="<?=$row?>-<?=$column?>" <?php
                            $rowColumn = $row . '-' . $column;
                             /** @var string $reservedSeats */
                             foreach ($reservedSeats as $seat) {
                                if ($seat === $rowColumn) {
                                    echo 'disabled="true"';
                                    break;
                                }
                            }
                        ?> >
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    </table>
    <button type="submit">Rezerwuj</button>
</form>
</body>
</html>
