<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Kino</title>
</head>
<body>
    <h1>Kino</h1>
    <ul>
        <li><a href="/movies">Filmy</a></li>
        <li><a href="/halls">Sale</a></li>
    </ul>
    <?php /** @var bool $logged */?>
    <?php if (!$logged): ?>
        <button onclick="window.location.href='./users/login'">Logowanie</button>
        <button onclick="window.location.href='./users/register'">Rejestracja</button>
    <?php else: ?>
        <button onclick="window.location.href='./users/show/<?=$_SESSION['user_id']?>'">Moje rezerwacje</button>
        <button onclick="window.location.href='./users/logout'">Wyloguj</button>
    <?php endif; ?>
</body>
</html>
