<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Film <?=/** @var TYPE_NAME $movie */
        $movie->getTitle() ?>
    </title>
</head>
<body>
    <h1>Film <?= $movie->getTitle() ?></h1>
    <p>Data: <?= date_format($movie->getDate(), 'Y-m-d H:i:s') ?></p>
    <p>Sala: <?= $movie->getHall() ?></p>
</body>
</html>
