<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sale:</title>
</head>
<body>
<h1>Sale:</h1>
<ul>
    <?php /** @var TYPE_NAME $halls */
    foreach ($halls as $hall): ?>
        <li>
            <a href="/halls/show/<?= $hall->getId() ?>">
                <?= $hall->getName() ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
</body>
</html>
