<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Film <?=/** @var \App\Models\Hall $hall */
        $hall->getName() ?>
    </title>
</head>
<body>
<h1><?= $hall->getName() ?></h1>
<p>Miejsca: <?= $hall->getRows() * $hall->getColumns() ?></p>
<h3>Filmy:</h3>
<table>
    <tr>
        <th>Tytuł</th>
        <th>Data</th>
    </tr>
    <?php /** @var \App\Models\Movie $movies */
    foreach ($movies as $movie): ?>
        <tr>
            <td>
                <a href="/movies/show/<?= $movie->getId() ?>">
                    <?= $movie->getTitle() ?>
                </a>
            </td>
            <td><?= date_format($movie->getDate(), 'Y-m-d H:i:s') ?></td>
        </tr>
    <?php endforeach; ?>
</table>
</body>
</html>

