<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Logowanie</title>
</head>
<body>
<h1>Logowanie:</h1>
<form action="/users/login" method="POST">
    <div>
        <label for="username">Nazwa użytkownika:</label>
        <input type="text" name="username" id="username">
    </div>
    <br>
    <div>
        <label for="password">Hasło:</label>
        <input type="password" name="password" id="password">
    </div>
    <br>
    <span style="color: red;"><?php if(isset($flash)) echo $flash . '<br>'?></span>
    <button type="submit">Zaloguj</button>
</form>
</body>
</html>
