<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <?php /** @var TYPE_NAME $user */ ?>
    <title>
        <?=$user->getUsername() ?>
    </title>
</head>
<body>
<h1><?= $user->getName() ?></h1>
<h3>Rezerwacje:</h3>
<table>
    <tr>
        <th>Tytuł</th>
        <th>Data</th>
    </tr>
    <?php /** @var TYPE_NAME $reservations */
    foreach ($reservations as $reservation): ?>
        <tr>
            <td>
                <a href="/movies/show/<?= $reservation->getId() ?>">
                    <?= $reservation->getTitle() ?>
                </a>
            </td>
            <td><?= date_format($reservation->getDate(), 'Y-m-d H:i:s') ?></td>
        </tr>
    <?php endforeach; ?>
</table>
</body>
</html>


